title: Artem Shramko
author: Artem Shramko
email: artem@shram.co
<<<<<<< HEAD
description: >- # this means to ignore newlines until "baseurl:"
  My portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shram.co/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  shramkoartem
linkedin_username: artemshramko
instagram_username: shram.co


=======
description: >- # this means to ignore newlines until "show_excerpts:"
  Hit me up if you are interested in hiring me as Data Scientist.

# set to true to show excerpts on the homepage

markdown: kramdown
show_excerpts: True
highlighter: rouge
mathjax: true
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    github:  shramkoartem
    rss: rss
    instagram: shram.co
    linkedin: artemshramko
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll

    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: shram_co
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
url: "https://shram.co/"
>>>>>>> 0da5c2c79d61ba85ec7161406f2078283eae3b71
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
